[package]
name = "shuttle-template-yew"
version = "1.0.0"
edition = "2021"

[dependencies]
axum = "0.6.19"
shuttle-axum = "0.22.0"
shuttle-runtime = "0.22.0"
shuttle-static-folder = "0.22.0"
tokio = "1.29.1"
tower-http = { version = "0.4.0", features = [ "fs"] }
